require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.1'
use_frameworks!

target 'ServicexSdkRnExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  #pod 'CredifyServiceX'
     
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.92.0', 'Flipper-Folly' => '2.6.7',  'Flipper-RSocket' => '1.4.3' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
  
  pod 'servicex-rn', :path => '../..'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
